#!/bin/bash
# koji-add-user: Add a new user to Koji

# Set us some variables for use later
BASEDIR="/etc/pki/koji"
CERTDIR="$BASEDIR/certs"
HOMEDIR="/heroes/u1"
PGM="koji-add-user"

# Sanity checks
if [ $# -ne 1 ]; then
    # Number of arguments is not equal to 1
    echo "$PGM: Error: Exactly one argument expected."
    exit 1
elif [ $HOSTNAME != "omachi.rutgers.edu" ]; then
    echo "$PGM: This script should only be done on omachi."
    exit 1
elif [ $USER != "root" ]; then
    echo "$PGM: Run this script as root."
    exit 1
elif [ ! -d $BASEDIR ]; then
    echo "$PGM: Fatal: The directory $BASEDIR doesn't exist."
    exit 1
fi

# Store the name of the new user - for clarity
NEWUSER=$1

case $NEWUSER in
    --help|-h|help)
        # Invoking help
        echo "Usage: $PGM <user>"
        echo "This should be run as someone with Koji admin access."
        exit 0
        ;;
    root)
        # Someone did `$PGM root`
        echo "Warning: Why are you adding root to Koji? Exiting."
        exit 1
        ;;
    *)
        # Check to make sure the user exists
        if ! id $NEWUSER > /dev/null 2>&1 ; then
            echo "$PGM: Error: User $NEWUSER does not exist."
            exit 1
        elif [ ! -d $HOMEDIR/$NEWUSER ]; then
            echo "$PGM: Error: User $NEWUSER doesn't have a home directory."
            exit 1
        fi
        ;;
esac

# Do the actual adding in Koji
koji add-user $NEWUSER
koji grant-permission admin $NEWUSER

# Exit if a command fails
set -e

# This is based off of Fedora docs and our OSS Wiki documentation
cd $BASEDIR
openssl genrsa -out $BASEDIR/certs/$NEWUSER.key 2048

echo "Creating certificate..."
openssl req -config $BASEDIR/ssl.cnf -new -nodes -out $BASEDIR/certs/$NEWUSER.csr -key $BASEDIR/certs/$NEWUSER.key
openssl ca -config $BASEDIR/ssl.cnf -keyfile $BASEDIR/private/koji_ca_cert.key -cert $BASEDIR/koji_ca_cert.crt -out $CERTDIR/$NEWUSER.crt -outdir $CERTDIR -infiles $CERTDIR/$NEWUSER.csr
cat $CERTDIR/$NEWUSER.crt $CERTDIR/$NEWUSER.key > $BASEDIR/$NEWUSER.pem

# Copy the certificates in the certificate directory to their home directory
echo "Copying certificates..."
cp $BASEDIR/$NEWUSER.pem $HOMEDIR/$NEWUSER/.fedora.cert

if [ -f $BASEDIR/koji_ca_cert ]; then
    cp $BASEDIR/koji_ca_cert $HOMEDIR/$NEWUSER/.fedora-upload-ca.cert
    cp $BASEDIR/koji_ca_cert $HOMEDIR/$NEWUSER/.fedora-server-ca.cert
elif [ -f $BASEDIR/koji_ca_cert.crt ]; then
    cp $BASEDIR/koji_ca_cert.crt $HOMEDIR/$NEWUSER/.fedora-upload-ca.cert
    cp $BASEDIR/koji_ca_cert.crt $HOMEDIR/$NEWUSER/.fedora-server-ca.cert
else
    echo "$PGM: Fatal: $BASEDIR/koji_ca_cert does not exist."
    echo "To fix this, generate/find the certificate again, and then copy it to your home directory as ~/.fedora-upload-ca.cert and ~/.fedora-server-ca.cert."
    exit 1
fi

# Finally, some final instructions on installation
echo -e "\nComplete. You now have three certificates in your home directory:"
echo -e "\t$HOMEDIR/$NEWUSER/.fedora.cert"
echo -e "\t$HOMEDIR/$NEWUSER/.fedora-upload-ca.cert"
echo -e "\t$HOMEDIR/$NEWUSER/.fedora-server-ca.cert"
echo "To use Koji on a build machine, copy these certificates there:"
echo -e "\t$ scp $HOMEDIR/$NEWUSER/.fedora* $NEWUSER@opus3:~/."
